# Generated by Django 5.0 on 2024-03-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarianmodule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetails',
            name='Picture',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
    ]
