# Generated by Django 5.0 on 2024-03-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarianmodule', '0002_bookdetails_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='Picture',
            field=models.ImageField(default='', upload_to='books/images'),
        ),
    ]
