# Generated by Django 5.0 on 2024-03-09 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0002_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
